version: '3.3'

services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: always
    ports:
      - "3000:3000"
  api:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8010:8010"
    command: uvicorn app:create_app --host 0.0.0.0 --port 8010 --reload